### ISSUE TITLE
new JLPT grades

### ISSUE THREAD

**Issue by MartinP7r** [davidluzgouveia/kanji-data#1]
Hi @davidluzgouveia,

thanks for providing this dataset! 
May I ask what exactly your source for the `jlpt_new` mappings is?  
Kanjidic only contains the old grades as far as I know.

Best regards,
Martin

**Comment by davidluzgouveia** [comment]
Hello @MartinP7r

At the time I compiled the dataset, I couldn't find any official source for the new JLPT grades. After some research, the study materials found here seemed like the closest I would be able to get: [http://www.tanos.co.uk/jlpt/](http://www.tanos.co.uk/jlpt/)

The data was extracted programmatically to avoid any errors, but unfortunately it seems that the URLs I used (which showed the kanji lists as HTML) are no longer working (e.g. [http://www.tanos.co.uk/jlpt/jlpt1/kanji/](http://www.tanos.co.uk/jlpt/jlpt1/kanji/)).

Might need to update the tool to get the information from one of the alternative formats (e.g. from the .anki file).

**Comment by MartinP7r** [comment]
Thank you @davidluzgouveia for getting back to me so quickly!

The same search for the official grades made me ask that question. 😅
It's strange that there doesn't seem to be an official easily accessible definitive list somewhere on their website.

**Comment by davidluzgouveia** [comment]
It sure is a pity! If some official source comes along I'll be sure to update the dataset :) Actually I'll probably attempt to update the dataset in a couple of days anyway, just in case there's been an update to any of the sources, since it's been a while now.

**Comment by MartinP7r** [comment]
Thank you! I'll make sure to leave a comment as well if I should ever come across something helpful.

Also:
I just saw this on the site you referenced.  
E.g. http://www.tanos.co.uk/jlpt/jlpt3/ has a section that says 
> Right, here's the deal. There's no official JLPT N3 vocabulary, kanji or grammar list. They have stated on their site they will not release any lists, just like TOEFL.
The new N1, N2, N4 and N5 levels are said to be at the same level as the old levels 1, 2, 3 and 4, so we can be sure of the content for N1, N4 and N5.
However N2 and N3 have to be estimated.

So, probably no official lists, ever. 
The rest somewhat matches what I read before about the new levels N2 and N3 being a split of the previous Level 2.
